version: '3.8'

services:

  python:
    build:
      context: ./python
    depends_on:
      - php

  mysqldb:
    container_name: mysqlASW
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: bot
    ports:
      - "3309:3306"  # Acesso ao MySQL
    volumes:
      - ./php/init.sql:/docker-entrypoint-initdb.d/init.sql  # Montar o script SQL

  php:
    build:
      context: ./php
    ports:
      - "8080:80"  # Acessar no navegador em http://localhost:8080
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysqldb